server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: productos-service
          uri: lb://productos-service
          predicates:
            - Path=/productos, /productos/**
        - id: ordenes-service
          uri: lb://ordenes-service
          predicates:
            - Path=/ordenes, /ordenes/**
        - id: pagos-service
          uri: lb://pagos-service
          predicates:
            - Path=/pagos, /pagos/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
